### ISSUE TITLE
Huawei_solar stopped working after update of HA core from 2023.5.4 to 2023.6.2

### ISSUE THREAD

**Issue by pjgrun** [Emilv2/huawei_solar#105]
Huawei_solar stopped working after update of HA core from 2023.5.4 to 2023.6.2.
I was running version a973aed of Huawei_solar. I installed version 57fd7e6, but HA reported error when checking configuration before HA restart.. Error message reported was:  platform error sensor.huawei_solar - exception importing custom_components.huawei_solar.sensor.
The only way to recover was to rollback HA core to version 2023.5.4
Is this a known issue?

**Comment by garzew2** [comment]
I had same situation. I had to restore configuration from backup. After that update goes with any problem.
But after update Huawei_solar to new version it stop to work. I make test on HA 2023.5.4 and 2023.6.2.

**Comment by garzew2** [comment]
This is my log when i update Huawei_solar 

`Logger: homeassistant.components.sensor
Source: custom_components/huawei_solar/sensor.py:181
Integration: Sensor (documentation, issues)
First occurred: 22:34:59 (1 occurrences)
Last logged: 22:34:59

Error while setting up huawei_solar platform for sensor
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/huawei_solar/registers.py", line 92, in decode
result = self.unit[result]
~~~~~~~~~^^^^^^^^
KeyError: 303

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/huawei_solar/sensor.py", line 181, in async_setup_platform
tmp = (await inverter.get(register)).value
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 215, in get
return (await self.get_multiple([name], slave))[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 254, in get_multiple
result = [await self._decode_response(registers[0], decoder)]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 207, in _decode_response
result = reg.decode(decoder, self)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/registers.py", line 94, in decode
raise DecodeError from err
huawei_solar.exceptions.DecodeError`

**Comment by pjgrun** [comment]
I am now stuck on version 2023.5.4 version of HA core. With version 2023.6.2 of HA core, both old and new version of Huawei_Solar fail. Only possibility appears to be to stay on HA core 2023.5.4.

**Comment by Jarobwo** [comment]
I have the same problem with the new version, can you fix it?  do i need to look for another integration?

**Comment by sdlafferty** [comment]
Same issue for me too.

**Comment by EmAnzi3** [comment]
Same for me.

**Comment by Trafal125** [comment]
Hi, same issue for me too. Any fix this problem?

**Comment by Stea73** [comment]
I had the same issue. I restored a backup and avoided to update the addon. So far it works. Let's hope a fix will be implemented soon

**Comment by Trafal125** [comment]
Hi, I update addons and I want get previous version - an older version. Anyone know how to download?

**Comment by Stea73** [comment]
Not an expert, but either you download the previous version in github and replace the files manually (but I'm not sure it will work) or you restore a full backup prior to the addon update (you may lose any change done after the update though).

**Comment by Trafal125** [comment]
Ok, I found old version addon:
https://github.com/Emilv2/huawei_solar/tree/a973aed9397b5e6a7ff0d88a1a53c41d5346211d/custom_components/huawei_solar
After restore from  backup HA Core and copy old version addons, everything works. Thank you for help

**Comment by pjgrun** [comment]
Any news? Still blocked with this issue and thus unable to update HA core beyond 2023.5.4.

**Comment by EmAnzi3** [comment]
I'm still stuck with this add-on not loaded.
I don't know if this might help but also from my mobile app FusionSolar I wasn't able to monitor my PV system. I addressed the issue changing inverter domain from intl.fusionsolar.huawei.com to region04eu5.fusionsolar.huawei.com

**Comment by pjgrun** [comment]
Finally migrated to https://github.com/wlcrs/huawei_solar and adapted my application accordingly. The new integration is working fine with latest OS and HA Core versions, and at least in my case, is compatible with emilv2 integration except for the sensor naming. The new integration has additional features, like exposure of a number of services, besides the sensors. Happy to have finally found a solution.
